import '/includes/css/variables.css';
import '/includes/css/site.css';
import '/includes/css/editor.css';
import '/includes/css/pattern-styles.css';
import '/includes/css/style-variations.css';

import "/includes/css/pattern-styles/accordions.css";
import "/includes/css/pattern-styles/alert-banner.css";
import "/includes/css/pattern-styles/all-announcements.css";
import "/includes/css/pattern-styles/announcement-block.css";
import "/includes/css/pattern-styles/blue-feature-blocks.css";
import "/includes/css/pattern-styles/contact-block.css";
import "/includes/css/pattern-styles/events-list.css";
import "/includes/css/pattern-styles/featured-resource.css";
import "/includes/css/pattern-styles/pathway-grid.css";
import "/includes/css/pattern-styles/pathways-block.css";
import "/includes/css/pattern-styles/quicklinks.css";
import "/includes/css/pattern-styles/sidebar-block.css";
import "/includes/css/pattern-styles/spotlight-cards.css";